using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel()]
public partial class DataSyncModel
{
    [RealtimeProperty(1, true, true)] private bool _state;
    [RealtimeProperty(2, true, true)] private string _message;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class DataSyncModel : RealtimeModel {
    public bool state {
        get {
            return _stateProperty.value;
        }
        set {
            if (_stateProperty.value == value) return;
            _stateProperty.value = value;
            InvalidateReliableLength();
            FireStateDidChange(value);
        }
    }
    
    public string message {
        get {
            return _messageProperty.value;
        }
        set {
            if (_messageProperty.value == value) return;
            _messageProperty.value = value;
            InvalidateReliableLength();
            FireMessageDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(DataSyncModel model, T value);
    public event PropertyChangedHandler<bool> stateDidChange;
    public event PropertyChangedHandler<string> messageDidChange;
    
    public enum PropertyID : uint {
        State = 1,
        Message = 2,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _stateProperty;
    
    private ReliableProperty<string> _messageProperty;
    
    #endregion
    
    public DataSyncModel() : base(null) {
        _stateProperty = new ReliableProperty<bool>(1, _state);
        _messageProperty = new ReliableProperty<string>(2, _message);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _stateProperty.UnsubscribeCallback();
        _messageProperty.UnsubscribeCallback();
    }
    
    private void FireStateDidChange(bool value) {
        try {
            stateDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireMessageDidChange(string value) {
        try {
            messageDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _stateProperty.WriteLength(context);
        length += _messageProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _stateProperty.Write(stream, context);
        writes |= _messageProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.State: {
                    changed = _stateProperty.Read(stream, context);
                    if (changed) FireStateDidChange(state);
                    break;
                }
                case (uint) PropertyID.Message: {
                    changed = _messageProperty.Read(stream, context);
                    if (changed) FireMessageDidChange(message);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _state = state;
        _message = message;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
